######################################################################
# Automatically generated by qmake (3.0) ?? 10? 1 23:50:07 2017
######################################################################

TEMPLATE = app
TARGET = youdao_dict
INCLUDEPATH += /usr/local/include/json-c
QT += widgets
LIBS += -lcurl
LIBS += -ljson-c
# Input
SOURCES += youdao_dict.cpp
